import type { Metadata } from "next";
import { public_sans } from "@/config/fonts";
import "./globals.css";
import { SideNav } from "@/ui/sidenav/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${public_sans.className} antialiased`}>  
        {children}
        <SideNav/> 
      </body>
    </html>
  );
}
