import type { Metadata } from "next";
import { public_sans } from "@/config/fonts";
import { SideNav } from "@/app/ui/sidenav/SideNav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${public_sans.className} antialiased`}>  
        <section className={'content_container'}>
          {children}
        </section>
      
        <SideNav/> 
      </body>
    </html>
  );
}
